spring.application.name=springDataJpa

#Connection Details with Postgres server
spring.datasource.url=jdbc:postgresql://localhost:5432/DB
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#This is used when we want to drop old table and create new one evrytime we run the command to add row
#spring.jpa.hibernate.ddl-auto=update

#This is used to smartly create table if table does not exist and append data simply if the table already exist
spring.jpa.hibernate.ddl-auto=update

#Shows the query it runs
spring.jpa.show-sql=true